{
 "title": "Boid Season 2 - Alpha Team View",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Global Boid Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "sum(boid_team_power)" }
   ]
  },
  {
   "title": "WCG total Jobs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "boid_total_results" }
   ]
  },
  {
   "title": "WCG Total Devices",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "boid_devices" }
   ]
  },
  {
   "title": "WCG Results Rank",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "boid_results_rank" }
   ]
  },
  {
   "title": "WCG Points Rank",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 18, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "boid_points_rank" }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 2 },
   "content": "![alt text](https://www.genereos.io/wp-content/uploads/2019/04/boid-logo.png)"
  },
  {
   "title": "WCG Average Points/Job",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 2 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "boid_total_points / boid_total_results"
    }
   ]
  },
  {
   "title": "Global Team Power vs Bonus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(boid_team_power)", "legendFormat": "global power" },
    { "expr": "sum(boid_team_bonus)", "legendFormat": "global bonus" }
   ]
  },
  {
   "title": "Total Team Bonuses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 4 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "sum(boid_team_bonus)" }
   ]
  },
  {
   "title": "Total Teams",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 6 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "count(boid_team_power)" }
   ]
  },
  {
   "title": "Top Team",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "topk(1,boid_team_power)", "legendFormat": "{{team_name}}" }
   ]
  },
  {
   "title": "Best Team Power",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 8 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    { "expr": "max(boid_team_power)" }
   ]
  },
  {
   "title": "Boid Team Power Market Share",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 10 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sort_desc(boid_team_power)", "legendFormat": "{{team_name}}" }
   ]
  },
  {
   "title": "Boid Team Power (top 6)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "topk(6,boid_team_power)", "legendFormat": "{{team_name}}" }
   ]
  },
  {
   "title": "Boid Team Bonus Market Share",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    { "expr": "sort_desc(boid_team_bonus)", "legendFormat": "{{team_name}}" }
   ]
  },
  {
   "title": "Boid Team Jobs (delta 2h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "delta(boid_total_results[2h])", "legendFormat": "jobs" },
    { "expr": "boid_total_results", "legendFormat": "tot jobs" }
   ]
  },
  {
   "title": "Boid Team Power ( rate of change 2h )",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "sum(boid_team_power) by (team_name)",
     "legendFormat": "{{team_name}}"
    }
   ]
  },
  {
   "title": "Boid Team Devices",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "boid_devices", "legendFormat": "devices" }
   ]
  },
  {
   "title": "Boid Team Results Rank",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "boid_results_rank", "legendFormat": "results rank" }
   ]
  },
  {
   "title": "Boid Team Points Rank",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 34 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    { "expr": "boid_points_rank", "legendFormat": "points rank" }
   ]
  }
 ]
}